### ISSUE TITLE
BitFox Engine Tries to send Notification even if Notify is is false 

### ISSUE THREAD

**Issue by benjamin-keil-crypto-worx** [benjamin-keil-crypto-worx/botfox#5]
Steps To Reproduce.

Use Builder Interface to create a Engine Instance
````js
let builder = require("bitfox").bitfox.builder; // import the builder interface
    let engine = builder()
        .requiredCandles(200)
        .sidePreference("long")
        .backtest(false)
        .pollRate(10)
        .public(true)
        .exchange("bybit")
        .symbol("ADAUSDT")
        .timeframe("15m")
        .amount(100)
        .profitPct(0.003)
        .fee(0.02)
        .key("FAKE_KEY")
        .secret("FAKE_SECRET")
        .life(false)
        .interval(10)
        .build(); 
        
    // Set up the Exchage Client
    await engine.setupAndLoadClient()
    
    // Leverage A Strategy from botfoxes strategy repository
    engine.applyStrategy(SuperTrend)
    // or Alternatively 
    let bitfox = require("bitfox").bitfox;
    engine.applyStrategy(bitfox.SuperTrend)
    
    // Set Up Event Handlers 
    engine.on('onMessage', (eventArgs) => {
        console.log(eventArgs)
    });
    engine.on('onError', (eventArgs) => {
        console.log(eventArgs)
    });
    engine.on('onOrderPlaced', (eventArgs) => {
        console.log(eventArgs)
    });
    engine.on('onOrderFilled', (eventArgs) => {
        console.log(eventArgs)
    });
    engine.on('onTradeComplete', (eventArgs) => {
        console.log(eventArgs)
    });
    engine.on('onStopLossTriggered', (eventArgs) => {
        console.log(eventArgs)
    });
    // SetUp Custom Event Handler (You need to fire the event yourself BotFox doesn't know about your Custom Event")
    engine.on('MyCustomEvent', (eventArgs) => {
        console.log(eventArgs)
    });
    
    // You could get the Event handler and fire an event by using below code
    engine.getEventEmitter().fireEvent("MyCustomEvent", {customEventData:"YourCustomEventData"})
    
    // Start The BotFox Engine
    await engine.run();
````

Expecetd Behaviour Engine runs without Error

Actual Behaviur 

````shell
{ customEventData: 'YourCustomEventData' }
[ERROR] ["TypeError","Cannot read properties of undefined (reading 'notify')","TypeError: Cannot read properties of undefined (reading 'notify')\n    at Timeout._onTimeout (C:\\Users\\benja\\develop\\bf-testing\\node_modules\\bitfox\\engine\\BitFox.js:349:42)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"]
TypeError: Cannot read properties of undefined (reading 'notify')
    at Timeout._onTimeout (C:\Users\benja\develop\bf-testing\node_modules\bitfox\engine\BitFox.js:349:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
````

**Comment by benjamin-keil-crypto-worx** [comment]
This Is Caused because we haven't implemented a notify check around the alerting block

We need to implement a notify check

````js
 if(result && [State.STATE_ENTER_SHORT,State.STATE_ENTER_LONG].includes(result.state)){
                    try{
                         if(me.notify && me.alerter !== null){ // <- this is new
                         await me.alerter.notify(me.params,`BitFox Strategy Alert ${me.params.symbol} \n State:${result.state} Context: ${result.context || "Strategy"}`)
                         }
                        
                    }catch(error){
                        Log.error(error);
                        me.eventHandler.fireEvent("onError", error);
                    }
                }
                if(!me.notifyOnly) {await this.executeStrategyContext(result, me)}
````

**Comment by benjamin-keil-crypto-worx** [comment]
Fix was applied will be rolled out in next release 0.0.2
